export const ZOOM_CHART = 'zoom_chart'
export const FETCH_CHART_SUCCESS = 'fetch_chart_success'
export const ADD_TRENDLINE = 'add_trendline'
export const FETCH_CHART_START  = 'fetch_chart_start'
export const MOVE_CHART  = 'move_chart'